### ISSUE TITLE
Enhancements for Plugin Optimization

### ISSUE THREAD

**Issue by Draghonir** [Btd20/SetHome#1]
Hi there,

I've been thoroughly impressed with the potential of this plugin, and I have a few suggestions that I believe could elevate its functionality even further:

Permission Configuration: It would be immensely beneficial to introduce a permission system that allows users to limit the number of homes, similar to the 'home.gui.1' This would offer greater flexibility and control over the plugin's usage.

Bed Home Integration: Incorporating the ability to set bed homes directly from the home menu would streamline the user experience significantly. It's a small tweak that can make a big difference in usability.

Discord URL Update: I've noticed that the Discord URL in the config.yml is currently not functional, leading to invitation failures. Updating this URL to a working one would ensure smoother communication and support channels for users.

Implementing these suggestions could greatly enhance the overall effectiveness and user satisfaction with the plugin. I'm eager to see these improvements come to fruition and contribute to its success.

**Comment by Btd20** [comment]
Hi, everything updated. Thanks for your suggestions!
